### ISSUE TITLE
Error: TypeError: Unable to determine the current version of @owner/repo on NPM.

### ISSUE THREAD

**Issue by cpotter302** [JS-DevTools/npm-publish#24]
Hello there, I am using npm https://npm.pkg.github.com as my npm package registry. Unfortunately i always get this error when it start my workflow. 
Full log comes here: 

Run JS-DevTools/npm-publish@v1
  with:
    token: ***
    registry: https://npm.pkg.github.com
    check-version: false
    package: package.json
    tag: latest
    dry-run: false
Error: TypeError: Unable to determine the current version of @cpotter302/ubuntu-welcome-page on NPM. 
Invalid Version: 
    at Object.getLatestVersion (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/npm.ts:57:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.npmPublish (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/npm-publish.ts:16:26)
    at main (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/action/index.ts:28:19)

TypeError: Invalid Version: 
    at new SemVer (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/dist/node_modules/semver/classes/semver.js:41:13)
    at Object.getLatestVersion (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/npm.ts:51:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.npmPublish (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/npm-publish.ts:16:26)
    at main (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/action/index.ts:28:19)

**Comment by RubenVerborgh** [comment]
Same error for us: https://github.com/solid/mashlib/runs/1510028311?check_suite_focus=true

The exact same workflow works fine on our other repositories.

**Comment by JamesMessinger** [comment]
This should now be fixed by PR #19, which was just released as version 1.4.1

**Comment by RubenVerborgh** [comment]
@JamesMessinger Not really, but it is fixed by #25.
