### ISSUE TITLE
Version 1.4.1 throws error

### ISSUE THREAD

**Issue by noah-friedman** [JS-DevTools/npm-publish#29]
Consistently receive an error when attempting to run version 1.4.1 of this action. See failed workflow steps [here](https://github.com/noahfriedman-ca/components/runs/1637112911?check_suite_focus=true) and [here](https://github.com/noahfriedman-ca/components/runs/1637127985?check_suite_focus=true).

LOG:
```
Run JS-DevTools/npm-publish@v1
  with:
    token: ***
    access: public
    registry: https://registry.npmjs.org/
    package: package.json
    tag: latest
    dry-run: false
    check-version: true
Error: Cannot find module '../internal/parse-options'
Require stack:
- /home/runner/work/_actions/JS-DevTools/npm-publish/v1/dist/node_modules/semver/classes/semver.js
- /home/runner/work/_actions/JS-DevTools/npm-publish/v1/dist/node_modules/semver/index.js
- /home/runner/work/_actions/JS-DevTools/npm-publish/v1/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/dist/node_modules/semver/classes/semver.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
```

**WORKAROUND**: Use version 1.4.0 (in your Github Workflow write `uses: JS-DevTools/npm-publish@v1.4.0` instead of `uses: JS-DevTools/npm-publish@v1`

**Comment by JamesMessinger** [comment]
Crap!  Sorry about that!  Fixing it now...

**Comment by JamesMessinger** [comment]
Ok, this should be fixed now.  You can use `JS-DevTools/npm-publish@v1` or `JS-DevTools/npm-publish@v1.4.3`

**Comment by noah-friedman** [comment]
I can confirm this works. Thanks!
