### ISSUE TITLE
Package successfully publishes to npmjs but also throws a 403

### ISSUE THREAD

**Issue by Yrlish** [JS-DevTools/npm-publish#37]
My workflow successfully publishes the package, but then it throws an 403 error that it is already published. Is it getting published twice?

https://github.com/Yrlish/eslint-config/blob/master/.github/workflows/push.yml

```
2021-05-06T17:48:44.3770137Z ##[group]Run JS-DevTools/npm-publish@v1
2021-05-06T17:48:44.3770604Z with:
2021-05-06T17:48:44.3771391Z   token: ***
2021-05-06T17:48:44.3771722Z   access: public
2021-05-06T17:48:44.3772239Z   registry: https://registry.npmjs.org/
2021-05-06T17:48:44.3772773Z   package: package.json
2021-05-06T17:48:44.3773129Z   tag: latest
2021-05-06T17:48:44.3773426Z   dry-run: false
2021-05-06T17:48:44.3773785Z   check-version: true
2021-05-06T17:48:44.3774566Z ##[endgroup]
2021-05-06T17:48:46.9993816Z npm notice 
2021-05-06T17:48:47.0006999Z npm notice 📦  @yrlish/eslint-config@1.0.5
2021-05-06T17:48:47.0010525Z npm notice === Tarball Contents === 
2021-05-06T17:48:47.0028823Z npm notice 161B react.js     
2021-05-06T17:48:47.0033194Z npm notice 600B typescript.js
2021-05-06T17:48:47.0034478Z npm notice 257B package.json 
2021-05-06T17:48:47.0035358Z npm notice 503B README.md    
2021-05-06T17:48:47.0036787Z npm notice === Tarball Details === 
2021-05-06T17:48:47.0053819Z npm notice name:          @yrlish/eslint-config                   
2021-05-06T17:48:47.0055146Z npm notice version:       1.0.5                                   
2021-05-06T17:48:47.0056244Z npm notice package size:  736 B                                   
2021-05-06T17:48:47.0057095Z npm notice unpacked size: 1.5 kB                                  
2021-05-06T17:48:47.0058112Z npm notice shasum:        937dc9c1be79b36fb047ffc407fc15a12ad6a086
2021-05-06T17:48:47.0059691Z npm notice integrity:     sha512-N8kwW6U6tUcpF[...]nICbf0hZtQyOA==
2021-05-06T17:48:47.0061900Z npm notice total files:   4                                       
2021-05-06T17:48:47.0062964Z npm notice 
2021-05-06T17:48:49.8407528Z 
2021-05-06T17:48:49.8409295Z > @yrlish/eslint-config@1.0.5 publish .
2021-05-06T17:48:49.8410804Z > npm publish --access public
2021-05-06T17:48:49.8411418Z 
2021-05-06T17:48:50.2657381Z npm notice 
2021-05-06T17:48:50.2670244Z npm notice 📦  @yrlish/eslint-config@1.0.5
2021-05-06T17:48:50.2673373Z npm notice === Tarball Contents === 
2021-05-06T17:48:50.2690973Z npm notice 161B react.js     
2021-05-06T17:48:50.2706591Z npm notice 600B typescript.js
2021-05-06T17:48:50.2707379Z npm notice 257B package.json 
2021-05-06T17:48:50.2708334Z npm notice 503B README.md    
2021-05-06T17:48:50.2709024Z npm notice === Tarball Details === 
2021-05-06T17:48:50.2710667Z npm notice name:          @yrlish/eslint-config                   
2021-05-06T17:48:50.2711541Z npm notice version:       1.0.5                                   
2021-05-06T17:48:50.2712367Z npm notice package size:  736 B                                   
2021-05-06T17:48:50.2713873Z npm notice unpacked size: 1.5 kB                                  
2021-05-06T17:48:50.2714838Z npm notice shasum:        937dc9c1be79b36fb047ffc407fc15a12ad6a086
2021-05-06T17:48:50.2716163Z npm notice integrity:     sha512-N8kwW6U6tUcpF[...]nICbf0hZtQyOA==
2021-05-06T17:48:50.2717092Z npm notice total files:   4                                       
2021-05-06T17:48:50.2717732Z npm notice 
2021-05-06T17:48:50.7387303Z npm ERR! code E403
2021-05-06T17:48:50.7446322Z npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@yrlish%2feslint-config - You cannot publish over the previously published versions: 1.0.5.
2021-05-06T17:48:50.7447944Z npm ERR! 403 In most cases, you or one of your dependencies are requesting
2021-05-06T17:48:50.7448996Z npm ERR! 403 a package version that is forbidden by your security policy.
2021-05-06T17:48:50.7499681Z 
2021-05-06T17:48:50.7502366Z npm ERR! A complete log of this run can be found in:
2021-05-06T17:48:50.7503508Z npm ERR!     /home/runner/.npm/_logs/2021-05-06T17_48_50_744Z-debug.log
2021-05-06T17:48:50.7610005Z npm ERR! code ELIFECYCLE
2021-05-06T17:48:50.7610534Z npm ERR! errno 1
2021-05-06T17:48:50.7689051Z npm ERR! @yrlish/eslint-config@1.0.5 publish: `npm publish --access public`
2021-05-06T17:48:50.7690553Z npm ERR! Exit status 1
2021-05-06T17:48:50.7691927Z npm ERR! 
2021-05-06T17:48:50.7692985Z npm ERR! Failed at the @yrlish/eslint-config@1.0.5 publish script.
2021-05-06T17:48:50.7693928Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-05-06T17:48:50.7764628Z npm WARN Local package.json exists, but node_modules missing, did you mean to install?
2021-05-06T17:48:50.7768160Z 
2021-05-06T17:48:50.7768825Z npm ERR! A complete log of this run can be found in:
2021-05-06T17:48:50.7770529Z npm ERR!     /home/runner/.npm/_logs/2021-05-06T17_48_50_769Z-debug.log
2021-05-06T17:48:50.8162402Z ##[error]Error: Unable to publish @yrlish/eslint-config v1.0.5 to NPM. 
npm publish --access public exited with a status of 1.
    at Object.publish (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/npm.ts:112:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

ProcessError: npm publish --access public exited with a status of 1.
    at normalizeResult (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/node_modules/@jsdevtools/ez-spawn/lib/normalize-result.js:31:1)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/node_modules/@jsdevtools/ez-spawn/lib/async.js:79:1)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

**Comment by Yrlish** [comment]
nvm, solved it. I had the following in my `package.json`

```
  "scripts": {
    "publish": "npm publish --access public"
  },
```
