### ISSUE TITLE
Invalid Version:  2023.01.17

### ISSUE THREAD

**Issue by tpluscode** [JS-DevTools/npm-publish#70]
Please see https://github.com/zazuko/rdf-vocabularies/actions/runs/3938156395/jobs/6736517234#step:5:10

```
Error: TypeError: Unable to parse package.json 
Invalid Version: 2023.01.17
    at Object.readManifest (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/read-manifest.ts:47:[11](https://github.com/zazuko/rdf-vocabularies/actions/runs/3938156395/jobs/6736517234#step:5:12))
    at Object.npmPublish (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/npm-publish.ts:15:18)
    at main (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/action/index.ts:28:19)
```

Was fine when releasing `2022.11.28`: https://github.com/zazuko/rdf-vocabularies/actions/runs/3568510580/jobs/5997458263

**Comment by hardillb** [comment]
The leading `0` on the `01` minor version is not valid

https://semver.org/#spec-item-2
